services:
  app:
    build: .
    image: fc-cms:latest
    container_name: fc-cms-app
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=${DB_URL:-jdbc:mysql://host.docker.internal:3306/fc_cms?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-password}
      - APP_JWT_SECRET=${APP_JWT_SECRET:-your_jwt_secret_here}
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS:-https://yourdomain.com}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./uploads:/application/uploads
    deploy:
      resources:
        limits:
          memory: 2G
    networks:
      - cms-network

  nginx:
    image: nginx:stable-alpine
    container_name: fc-cms-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
    volumes:
      # 显示配置和指定nginx主配置
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/certs:/etc/nginx/certs:ro
      - ./fc-cms-web/dist:/usr/share/nginx/html/admin:ro
      - ./uploads:/usr/share/nginx/html/uploads:ro
    depends_on:
      - app
    deploy:
      resources:
        limits:
          memory: 200M
    networks:
      - cms-network

  # redis:
  #   image: redis:alpine
  #   container_name: fc-cms-redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 200M
  #   networks:
  #     - cms-network

networks:
  cms-network:
    driver: bridge
